import Foundation

enum FieldLanguage: String, CaseIterable, Identifiable {
    case spanish = "es"
    case english = "en"

    static let preferenceKey = "field.appLanguage"

    var id: String { rawValue }

    var name: String {
        switch self {
        case .spanish: "Español"
        case .english: "English"
        }
    }

    var locale: Locale {
        Locale(identifier: self == .spanish ? "es-ES" : "en-US")
    }
}

enum FieldLocalization {
    private static let spanish: [String: String] = [
        "Quick Capture": "Captura rápida",
        "Focus Search": "Enfocar búsqueda",
        "Test, compare and document what works.": "Prueba, compara y documenta lo que funciona.",
        "Build a visual workbench from references, a prompt, a tool and the settings that matter. Each Run stays reproducible while you learn.": "Crea un espacio visual con referencias, un prompt, una herramienta y los ajustes necesarios. Cada ejecución conserva su configuración para que puedas aprender de los resultados.",
        "INGREDIENTS": "ELEMENTOS",
        "RUNS": "EJECUCIONES",
        "COMPARE": "COMPARAR",
        "LEARN": "APRENDER",
        "Recent Experiments": "Experimentos recientes",
        "Your documented Runs will appear here.": "Aquí aparecerán las ejecuciones que documentes.",
        "New Experiment": "Nuevo experimento",
        "Start with a question, or load a Recipe as a starting point.": "Empieza con una pregunta o carga una receta como punto de partida.",
        "Choose later": "Elegir más tarde",
        "Blank setup": "Configuración vacía",
        "No project": "Ningún proyecto",
        "Browse Collect, drag images here, or add an existing reference.": "Explora Recopilar, arrastra imágenes aquí o añade una referencia existente.",
        "Choose a tool": "Elige una herramienta",
        "External": "Externa",
        "Create a Run when the setup is ready. It keeps its own prompt, references, tool and settings.": "Crea una ejecución cuando la configuración esté lista. Guardará su propio prompt, referencias, herramienta y ajustes.",
        "DROP RESULT HERE": "SUELTA AQUÍ EL RESULTADO",
        "Compare becomes available after two Runs have results.": "Podrás comparar cuando dos ejecuciones tengan resultados.",
        "REFERENCES": "REFERENCIAS",
        "Reuse existing Collect entities. Nothing is duplicated.": "Reutiliza elementos existentes de Recopilar. No se duplican.",
        "Insert from Learn": "Insertar desde Aprender",
        "Choose Prompt Blocks to include in this setup.": "Elige los bloques de prompt que quieras incluir en esta configuración.",
        "Create Prompt Blocks in Learn first.": "Primero crea bloques de prompt en Aprender.",
        "RESULT": "RESULTADO",
        "SETTINGS SNAPSHOT": "AJUSTES GUARDADOS",
        "STATUS": "ESTADO",
        "OBSERVATION": "OBSERVACIÓN",
        "Select a Run": "Selecciona una ejecución",
        "Its result, snapshot settings, status, evaluation and observation will appear here.": "Aquí aparecerán el resultado, los ajustes guardados, el estado, la evaluación y la observación.",
        "Add Tool": "Añadir herramienta",
        "Tool Presets": "Preajustes de herramientas",
        "No presets saved for this tool yet.": "Aún no hay preajustes guardados para esta herramienta.",
        "Save Tool Preset": "Guardar preajuste de herramienta",
        "Save the current model and settings for reuse.": "Guarda el modelo y los ajustes actuales para reutilizarlos.",
        "Model": "Modelo",
        "Use in Experiment": "Usar en experimento",
        "Delete": "Eliminar",
        "Cancel": "Cancelar",
        "Create Experiment": "Crear experimento",
        "Import": "Importar",
        "Paste": "Pegar",
        "+ Block": "+ Bloque",
        "Copy Prompt": "Copiar prompt",
        "+ Add Tool": "+ Añadir herramienta",
        "Presets": "Preajustes",
        "Save Preset": "Guardar preajuste",
        "+ Add Setting": "+ Añadir ajuste",
        "Create Run": "Crear ejecución",
        "Save as Learning": "Guardar como aprendizaje",
        "Save Best Run as Recipe": "Guardar la mejor ejecución como receta",
        "Remove": "Quitar",
        "Done": "Hecho",
        "Insert": "Insertar",
        "Add Result": "Añadir resultado",
        "Replace Result": "Sustituir resultado",
        "Save Run Changes": "Guardar cambios de la ejecución",
        "Duplicate Run to Ingredients": "Duplicar ejecución en elementos",
        "Select Best Result": "Seleccionar mejor resultado",
        "Use in Lab": "Usar en Laboratorio",
        "Setup copied from the selected Run. Change one ingredient, then create a new Run.": "Configuración copiada de la ejecución seleccionada. Cambia un elemento y crea una ejecución nueva.",
        "Add reference": "Añadir referencia",
        "Saved to Learn": "Guardado en Aprender",
        "Recipe saved": "Receta guardada",
        "Connections": "Conexiones",
        "Context": "Contexto",
        "Experiment title": "Título del experimento",
        "What am I trying to learn?": "¿Qué quiero aprender?",
        "Key": "Clave",
        "Value": "Valor",
        "Unit": "Unidad",
        "Name": "Nombre",
        "Category": "Categoría",
        "Website / launch URL": "Sitio web o URL de inicio",
        "Preset name": "Nombre del preajuste",
        "New experiment title": "Título del nuevo experimento",
        "Settings": "Ajustes",
        "Search experiments": "Buscar experimentos",
        "Search Learn": "Buscar en Aprender",
        "Add Learning": "Añadir aprendizaje",
        "Learnings": "Aprendizajes",
        "Recipes": "Recetas",
        "Prompt Blocks": "Bloques de prompt",
        "No matching references": "No hay referencias que coincidan",
        "Try another search or change the selected filters.": "Prueba otra búsqueda o cambia los filtros seleccionados.",
        "No matching knowledge": "No hay conocimientos que coincidan",
        "Try another search or choose a different knowledge type.": "Prueba otra búsqueda o elige otro tipo de conocimiento.",
        "Clear search and filters": "Borrar búsqueda y filtros",
        "Starting tool": "Herramienta inicial",
        "Start from Recipe": "Empezar desde una receta",
        "Project": "Proyecto",
        "Workbench mode": "Modo de trabajo",
        "Tool": "Herramienta",
        "Status": "Estado",
        "Evaluation": "Evaluación",
        "Existing Experiment": "Experimento existente",
        "Knowledge type": "Tipo de conocimiento",
        "AI connections": "Conexiones de IA",
        "Activity": "Actividad",
        "Review agent actions": "Revisa las acciones de los agentes",
        "Projects": "Proyectos",
        "Organize your experiments": "Organiza tus experimentos",
        "Tools": "Herramientas",
        "Shared tool metadata": "Metadatos compartidos de herramientas",
        "Flow": "Flujo",
        "Flows": "Flujos",
        "Advanced reusable methods": "Métodos reutilizables avanzados",
        "MCP server starting": "Iniciando el servidor MCP",
        "MCP server stopping": "Deteniendo el servidor MCP",
        "MCP server active": "Servidor MCP activo",
        "MCP server stopped": "Servidor MCP detenido",
        "Setup": "Configuración",
        "run": "ejecución",
        "runs": "ejecuciones",
        "No tool": "Sin herramienta",
        "External workflow · copy prompt, open the tool, then bring the result back.": "Flujo externo · copia el prompt, abre la herramienta y vuelve aquí con el resultado.",
        "Duplicated from": "Duplicado de",
        "Changed from": "Cambios respecto a",
        "change": "cambio",
        "changes": "cambios",
        "Run": "Ejecución",
        "Collect": "Recopilar",
        "Lab": "Laboratorio",
        "Learn": "Aprender",
        "Creative memory": "Memoria creativa",
        "A clear view of what is becoming useful.": "Una vista clara de lo que empieza a ser útil.",
        "Current set": "Conjunto actual",
        "Save as Recipe": "Guardar como receta",
        "Document a repeatable creative method so you can reuse it.": "Documenta un método creativo repetible para poder reutilizarlo.",
        "Add the first step to turn this method into an executable guide.": "Añade el primer paso para convertir este método en una guía ejecutable.",
        "No recipe": "Sin receta",
        "Add steps to this flow before starting it.": "Añade pasos a este flujo antes de iniciarlo.",
        "No connected knowledge yet.": "Aún no hay conocimiento conectado.",
        "No connected visual references yet.": "Aún no hay referencias visuales conectadas.",
        "Agent proposals will appear here for review.": "Las propuestas de los agentes aparecerán aquí para revisarlas.",
        "This Mac only · 127.0.0.1": "Solo este Mac · 127.0.0.1",
        "Port %@ · local HTTP protected with a token": "Puerto %@ · HTTP local protegido con token",
        "Regenerating the token stops the server to revoke the previous one. Start it again before reconnecting the AI tools.": "Regenerar el token detiene el servidor para revocar el anterior. Inícialo de nuevo antes de reconectar las IA.",
        "Open prompt deck": "Abrir el mazo de prompts",
        "Open inbox": "Abrir la bandeja",
        "View projects": "Ver proyectos",
        "Edit": "Editar",
        "Save": "Guardar",
        "Choose image": "Elegir imagen",
        "Save recipe": "Guardar receta",
        "Start flow": "Iniciar flujo",
        "Delete step": "Eliminar paso",
        "Add step": "Añadir paso",
        "Save step": "Guardar paso",
        "Archive": "Archivar",
        "Add from library": "Añadir desde la biblioteca",
        "Reject": "Rechazar",
        "Approve": "Aprobar",
        "Regenerate token": "Regenerar token",
        "Learning": "Aprendizaje",
        "Reference": "Referencia",
        "Note": "Nota",
        "Open FIELD LAB": "Abrir FIELD LAB",
        "Create prompt": "Crear prompt",
        "Blocks": "Bloques",
        "Title": "Título",
        "Tags": "Etiquetas",
        "Title (optional)": "Título (opcional)",
        "Recipe title": "Título de la receta",
        "Step title": "Título del paso",
        "What happens in this step?": "¿Qué ocurre en este paso?",
        "Prompt or working template": "Prompt o plantilla de trabajo",
        "Private notes": "Notas privadas",
        "Flow title": "Título del flujo",
        "What does this method achieve?": "¿Qué consigue este método?",
        "Project title": "Título del proyecto",
        "One-line summary": "Resumen en una línea",
        "Summary": "Resumen",
        "Creative direction": "Dirección creativa",
        "Constraints": "Restricciones",
        "Deliverables": "Entregables",
        "Always remember": "Recordar siempre",
        "Website (optional)": "Web (opcional)",
        "I use it for": "La uso para",
        "Works well for": "Funciona bien para",
        "Common issues": "Problemas habituales",
        "New capture": "Nueva captura",
        "Original URL": "URL original",
        "Why did I save this?": "¿Por qué guardé esto?",
        "Add attribute": "Añadir atributo",
        "Unclassified": "Sin clasificar",
        "Pinned": "Fijadas",
        "Filter": "Filtros",
        "Use in LAB": "Usar en LAB",
        "Clear attributes": "Borrar atributos",
        "Manual visual attributes": "Atributos visuales manuales",
        "Detected source: %@": "Fuente detectada: %@",
        "Project references": "Referencias del proyecto",
        "Choose existing references. They remain shared library items.": "Elige referencias existentes. Seguirán siendo elementos compartidos de la biblioteca.",
        "Not connected to a project yet.": "Aún no está conectada a ningún proyecto.",
        "No connected experiments yet.": "Aún no hay experimentos conectados.",
        "No tool metadata yet.": "Aún no hay metadatos de herramientas.",
        "Classification can wait. Keep the source and the reason.": "La clasificación puede esperar. Conserva la fuente y el motivo.",
        "Tags can wait. Keep the source and the reason.": "Las etiquetas pueden esperar. Conserva la fuente y el motivo.",
        "There is no creative classification yet. This reference will appear under Unclassified.": "Aún no hay clasificación creativa. Esta referencia aparecerá en Sin clasificar.",
        "Create a project first to connect this reference.": "Crea primero un proyecto para conectar esta referencia.",
        "Choose existing references. They will remain shared library items.": "Elige referencias existentes. Seguirán siendo elementos compartidos de la biblioteca.",
        "Web": "Web",
        "Native app": "Aplicación nativa",
        "Manual": "Manual",
        "Clipboard": "Portapapeles",
        "Style": "Estilo",
        "Medium": "Medio",
        "Subject": "Sujeto",
        "Lighting": "Iluminación",
        "Composition": "Composición",
        "Mood": "Ambiente",
        "Color": "Color",
        "Prompt Block": "Bloque de prompt",
        "Recipe": "Receta",
        "Experiment": "Experimento",
        "Decision": "Decisión",
        "Resource": "Recurso",
        "Idea": "Idea",
        "Working memory": "Memoria de trabajo",
        "Canonical memory": "Memoria canónica",
        "Session summary": "Resumen de sesión",
        "New": "Nuevo",
        "Testing": "En pruebas",
        "Works": "Funciona",
        "Canonical": "Canónico",
        "Avoid": "Evitar",
        "Archived": "Archivado",
        "User": "Usuario",
        "Other agent": "Otro agente",
        "Prepared": "Preparado",
        "Completed": "Completado",
        "Failed": "Fallido",
        "Unrated": "Sin valorar",
        "Does not work": "No funciona",
        "Interesting": "Interesante",
        "Best result": "Mejor resultado",
        "Connected": "Conectada",
        "Text": "Texto",
        "Number": "Número",
        "Boolean": "Booleano",
        "Choice": "Opción",
        "No image attached": "No hay imagen adjunta",
        "Image attached": "Imagen adjunta",
        "Save reference": "Guardar referencia",
        "Edit reference": "Editar referencia",
        "References": "Referencias",
        "Why I saved this": "Por qué guardé esto",
        "Detected source": "Fuente detectada",
        "Saved": "Guardado",
        "Active": "Activo",
        "Inactive": "Inactivo",
        "Language": "Idioma",
        "Copy Prompt & Open": "Copiar prompt y abrir",
        "Not defined": "Sin definir",
        "Pending": "Pendiente",
        "Processing": "En curso",
        "Complete": "Completado",
        "Not available": "No disponible",
        "Proposed": "Propuso",
        "Approved": "Aprobó",
        "Read resource": "Leyó un recurso",
        "Searched knowledge": "Buscó conocimiento",
        "Searched references": "Buscó referencias",
        "Read reference": "Leyó una referencia",
        "Read project context": "Leyó el contexto del proyecto",
        "Read project constraints": "Leyó las restricciones del proyecto",
        "Read tool knowledge": "Leyó el conocimiento de la herramienta",
        "Read project decisions": "Leyó las decisiones del proyecto",
        "Read experiment": "Leyó un experimento",
        "Listed experiment runs": "Listó las ejecuciones del experimento",
        "Compared run metadata": "Comparó los metadatos de ejecuciones",
        "Searched experiments": "Buscó experimentos",
        "Read best run": "Leyó la mejor ejecución",
        "Read recipe": "Leyó una receta",
        "Read workflow": "Leyó un flujo",
        "Proposed reference tags": "Propuso etiquetas para una referencia",
        "Approved reference tags": "Aprobó etiquetas para una referencia",
        "Rejected proposal": "Rechazó una propuesta",
        "Added working note": "Añadió una nota de trabajo",
        "Saved session summary": "Guardó un resumen de sesión",
        "Snapshot": "Instantánea",
        "listos para combinar.": "listos para combinar.",
        "inserted": "insertado",
        "Step": "Paso",
        "of": "de",
        "Copy": "Copiar",
        "Copied": "Copiado",
        "Hide": "Ocultar",
        "Show": "Mostrar",
        "Copy template": "Copiar plantilla",
        "Finish": "Terminar",
        "Next": "Siguiente",
        "Previous": "Anterior",
        "Create Flow": "Crear flujo",
        "Save changes": "Guardar cambios",
        "New Flow": "Nuevo flujo",
        "Edit Flow": "Editar flujo",
        "New knowledge": "Nuevo conocimiento",
        "Edit knowledge": "Editar conocimiento",
        "New project": "Nuevo proyecto",
        "Edit project": "Editar proyecto",
        "Create project": "Crear proyecto",
        "Add tool": "Añadir herramienta",
        "Edit tool": "Editar herramienta",
        "Save tool": "Guardar herramienta",
        "Manage connection": "Gestionar conexión",
        "Configure connection": "Configurar conexión",
        "Pin": "Fijar",
        "Unpin": "Desfijar",
        "No description yet": "Aún no hay descripción",
        "Create another": "Crear otra",
        "What have you learned?": "¿Qué has aprendido?",
        "All": "Todo",
        "All sources": "Todas las fuentes",
        "Choose two or more blocks to create a reusable set.": "Elige dos o más bloques para crear un conjunto reutilizable.",
        "No flows yet": "Aún no hay flujos",
        "Nothing pending": "Nada pendiente",
        "New reference": "Nueva referencia",
        "Edit step": "Editar paso",
        "Instructions": "Instrucciones",
        "No instructions yet.": "Aún no hay instrucciones.",
        "Not written yet.": "Aún no escrito.",
        "Not written yet": "Aún no escrito",
        "Not written yet (feminine)": "Aún no escrita.",
        "Not written yet (feminine plural)": "Aún no escritas.",
        "Not written yet (masculine plural)": "Aún no escritos.",
        "Create a project": "Crear un proyecto",
        "Creative context containers for the work you are doing now.": "Contenedores de contexto para el trabajo que estás haciendo ahora.",
        "The local bridge is active.": "El puente local está activo.",
        "Connect Claude, Codex and compatible agents locally.": "Conecta Claude, Codex y agentes compatibles en local.",
        "Esperando a que termine la selección de puerto…": "Esperando a que termine la selección de puerto…",
        "Start the server before copying its configuration; the final port appears when it is active.": "Inicia el servidor antes de copiar la configuración; el puerto definitivo aparece al activarse.",
        "Saved in the macOS Keychain. Codex and Claude Code read it through a local helper when connecting; macOS may ask for permission the first time.": "Guardado en el Llavero de macOS. Codex y Claude Code lo consultan con un helper local al conectar; macOS puede pedir permiso la primera vez.",
        "Saved in the macOS Keychain. Set FIELD_MCP_TOKEN in the MCP client environment.": "Guardado en el Llavero de macOS. Configura FIELD_MCP_TOKEN en el entorno del cliente MCP.",
        "Codex reads FIELD_MCP_TOKEN from the process environment. Restart it if you just set that variable.": "Codex lee FIELD_MCP_TOKEN del entorno del proceso. Reinícialo si acabas de configurar esa variable.",
        "Codex reads the token from the Keychain through a local helper; the token is not stored in config.toml.": "Codex consulta el Llavero mediante un helper local; el token no queda en config.toml.",
        "Claude Code reads the token from the Keychain through a local helper; check the connection with /mcp.": "Claude Code consulta el Llavero mediante un helper local; verifica el estado con /mcp.",
        "Claude Code expands FIELD_MCP_TOKEN in its MCP settings. Check the connection with /mcp.": "Claude Code expande FIELD_MCP_TOKEN en su configuración MCP. Comprueba la conexión con /mcp.",
        "Copy Codex configuration": "Copiar configuración de Codex",
        "Copy Claude Code configuration": "Copiar configuración de Claude Code",
        "Copy setup prompt": "Copiar prompt de configuración",
        "Prompt copied": "Prompt copiado",
        "Save to FIELD LAB": "Guardar en FIELD LAB",
        "Endpoint": "Punto de conexión",
        "Local token": "Token local",
        "Start server": "Iniciar servidor",
        "Stop server": "Detener servidor",
        "Wait for the port selection to finish…": "Esperando a que termine la selección de puerto…",
        "No hay nada esperando tu atención.": "No hay nada esperando tu atención.",
        "El puente local está activo.": "El puente local está activo.",
        "Conecta Claude, Codex y agentes compatibles en local.": "Conecta Claude, Codex y agentes compatibles en local.",
        "Crea tu primer conjunto de lenguaje reutilizable.": "Crea tu primer conjunto de lenguaje reutilizable.",
        "Elige dos o más bloques para crear un conjunto reutilizable.": "Elige dos o más bloques para crear un conjunto reutilizable.",
        "Propuesta de": "Propuesta de",
        "Puerto": "Puerto",
        "HTTP local protegido con token": "HTTP local protegido con token",
        "item": "elemento",
        "items": "elementos",
        "The setup you are testing": "La configuración que estás probando",
        "No snapshots yet": "Aún no hay instantáneas",
        "Select the result that teaches you the most": "Elige el resultado del que más puedas aprender",
        "Add results to at least two Runs to compare": "Añade resultados a dos ejecuciones como mínimo para compararlas",
        "What did you learn?": "¿Qué has aprendido?",
        "No references yet": "Aún no hay referencias",
        "Save visual material in Collect first.": "Primero guarda material visual en Recopilar.",
        "Keep the techniques and recipes worth reusing.": "Conserva las técnicas y recetas que merecen la pena reutilizar.",
        "Add": "Añadir",
        "Your reusable knowledge lives here": "Aquí se reúne el conocimiento que puedes reutilizar.",
        "Conclusions become Learnings, Recipes and Prompt Blocks.": "Las conclusiones se convierten en aprendizajes, recetas y bloques de prompt.",
        "Choose something to reuse": "Elige algo para reutilizar",
        "Read each item in its complete context.": "Lee cada elemento en su contexto completo.",
        "Remove setting": "Quitar ajuste",
        "Best Result": "Mejor resultado",
        "All knowledge": "Todo el conocimiento",
        "Nothing here yet. Capture a small piece of knowledge to start building your field.": "Aún no hay nada aquí. Guarda un pequeño apunte para empezar a construir tu espacio de conocimiento.",
        "Save references, ideas and things you want to revisit.": "Guarda referencias, ideas y cosas que quieras volver a visitar.",
        "Save inspiration from anywhere": "Guarda inspiración desde cualquier lugar",
        "Bring an image, URL or note from Pinterest, Cosmos, Safari, Photos, LinkedIn and more. Its source stays attached so the reference remains useful.": "Trae una imagen, URL o nota desde Pinterest, Cosmos, Safari, Fotos, LinkedIn y más. La fuente queda vinculada para que la referencia siga siendo útil.",
        "Bring an image, URL or note. You can classify it later.": "Trae una imagen, URL o nota. Puedes clasificarla más tarde.",
        "Select an image to see its source, note, attributes and project connections.": "Selecciona una imagen para ver su fuente, nota, atributos y conexiones de proyecto.",
        "Choose a reference": "Elige una referencia",
        "Choose an experiment": "Elige un experimento",
        "Your Workbench is where references, prompts, tools and settings become reproducible Runs.": "Tu espacio de trabajo reúne referencias, prompts, herramientas y ajustes en ejecuciones reproducibles.",
        "Choose a knowledge item": "Elige un elemento de conocimiento",
        "Select an item to read its full context and connections.": "Selecciona un elemento para leer su contexto completo y sus conexiones.",
        "Choose the language you want to take to your next tool.": "Selecciona el lenguaje que quieres llevar a tu próxima herramienta.",
        "Your method, documented step by step, not automated.": "Tu método, documentado paso a paso, no automatizado.",
        "Context containers, not task boards.": "Contenedores de contexto, no tableros de tareas.",
        "Your experience with tools, not generic descriptions.": "Tu experiencia con las herramientas, no descripciones genéricas.",
        "Permanent memory always requires confirmation.": "La memoria permanente siempre pide confirmación.",
        "Actions in FIELD LAB, never private reasoning.": "Acciones en FIELD LAB, nunca razonamiento privado.",
        "A local memory bridge for Claude, Codex and compatible agents.": "Un puente de memoria local para Claude, Codex y agentes compatibles.",
        "Recent captures": "Capturas recientes",
        "Your latest notes will appear here.": "Tus últimas notas aparecerán aquí.",
        "Capture something": "Capturar algo",
        "Inbox is clear": "Tu bandeja está despejada",
        "Start building your field": "Empieza a construir tu campo",
        "New captures and working notes wait here until you are ready to organize them.": "Las nuevas capturas y notas de trabajo esperarán aquí hasta que estés listo para organizarlas.",
        "Flujos": "Flujos",
        "Proyectos": "Proyectos",
        "Herramientas": "Herramientas",
        "Por qué guardé esto": "Por qué guardé esto",
        "Fuente": "Fuente",
        "Atributos visuales": "Atributos visuales",
        "Etiquetas": "Etiquetas",
        "Experimentos relacionados": "Experimentos relacionados",
        "Metadatos": "Metadatos",
        "Procedencia": "Procedencia",
        "Conjunto de prompts": "Conjunto de prompts",
        "Recordar siempre": "Recordar siempre",
        "Conocimiento del proyecto": "Conocimiento del proyecto",
        "La uso para": "La uso para",
        "Funciona bien para": "Funciona bien para",
        "Problemas habituales": "Problemas habituales",
        "Conocimiento conectado": "Conocimiento conectado",
        "Punto de conexión": "Punto de conexión",
        "Token local": "Token local",
        "Conectar Codex": "Conectar Codex",
        "Conectar Claude Code": "Conectar Claude Code",
        "Configurar con una IA": "Configurar con una IA",
        "Permisos": "Permisos",
        "Leer conocimiento": "Leer conocimiento",
        "Buscar conocimiento": "Buscar conocimiento",
        "Añadir memoria de trabajo": "Añadir memoria de trabajo",
        "Proponer memoria permanente": "Proponer memoria permanente",
        "Escrituras canónicas directas": "Escrituras canónicas directas",
        "Eliminar conocimiento": "Eliminar conocimiento",
        "RELATED GUIDANCE": "ORIENTACIÓN RELACIONADA",
        "Nothing is waiting for your attention.": "No hay nada esperando tu atención.",
        "Choose a project": "Elige un proyecto",
        "A project gives agents a compact, lasting context package.": "Un proyecto ofrece a los agentes un paquete de contexto compacto y duradero.",
        "Choose a flow": "Elige un flujo",
        "A flow helps you repeat what already works.": "Un flujo te ayuda a repetir lo que ya funciona.",
        "A tool page gathers what you have learned about how it works for you.": "La página de una herramienta reúne el conocimiento acumulado sobre cómo funciona para ti.",
        "Choose a proposal": "Elige una propuesta",
        "Review what an agent wants to keep before turning it into memory.": "Revisa lo que un agente quiere conservar antes de convertirlo en memoria.",
        "Complete system labels": "Etiquetas del sistema",
        "PROMPT": "PROMPT",
        "TOOL": "HERRAMIENTA",
        "SETTINGS": "AJUSTES",
        "CONCLUSION": "CONCLUSIÓN",
        "One item": "Un elemento",
        "Capture": "Captura",
        "captures": "capturas",
        "capture": "captura",
        "blocks": "bloques",
        "block": "bloque",
        "steps": "pasos",
        "step": "paso",
        "Filters": "Filtros",
        "Source": "Fuente",
        "Search references": "Buscar referencias",
        "Search references, OCR and tags…": "Buscar referencias, OCR y etiquetas…",
        "Read knowledge": "Leer conocimiento",
        "Search knowledge": "Buscar conocimiento",
        "Add working memory": "Añadir memoria de trabajo",
        "Propose permanent memory": "Proponer memoria permanente",
        "Direct canonical writes": "Escrituras canónicas directas",
        "Delete knowledge": "Eliminar conocimiento",
        "Change": "Cambio",
    ]

    private static let english: [String: String] = [
        "Recopilar": "Collect",
        "Laboratorio": "Lab",
        "Aprender": "Learn",
        "Ajustes": "Settings",
        "Referencias": "References",
        "Aprendizajes": "Learnings",
        "Bloques de prompt": "Prompt Blocks",
        "Recetas": "Recipes",
        "Notas": "Notes",
        "Mazo de prompts": "Prompt Deck",
        "Herramientas": "Tools",
        "Flujos": "Flows",
        "Proyectos": "Projects",
        "Bandeja de IA": "AI Inbox",
        "Actividad": "Activity",
        "Servidor MCP": "MCP Server",
        "Memoria creativa": "Creative memory",
        "Una vista clara de lo que empieza a ser útil.": "A clear view of what is becoming useful.",
        "Captura rápida": "Quick capture",
        "Guarda un fragmento útil en FIELD LAB": "Save a useful fragment to FIELD LAB",
        "Añadir descripción": "Add description",
        "Conjunto actual": "Current set",
        "Sin herramienta": "No tool",
        "Guardar como receta": "Save as Recipe",
        "Documenta un método creativo repetible para poder reutilizarlo.": "Document a repeatable creative method so you can reuse it.",
        "Añade el primer paso para convertir este método en una guía ejecutable.": "Add the first step to turn this method into an executable guide.",
        "Sin receta": "No recipe",
        "Añade pasos a este flujo antes de iniciarlo.": "Add steps to this flow before starting it.",
        "Aún no hay conocimiento conectado.": "No connected knowledge yet.",
        "Aún no hay referencias visuales conectadas.": "No connected visual references yet.",
        "Las propuestas de los agentes aparecerán aquí para revisarlas.": "Agent proposals will appear here for review.",
        "Solo este Mac · 127.0.0.1": "This Mac only · 127.0.0.1",
        "Regenerar el token detiene el servidor para revocar el anterior. Inícialo otra vez antes de reconectar las IA.": "Regenerating the token stops the server to revoke the previous one. Start it again before reconnecting the AI tools.",
        "Abrir mazo de prompts": "Open prompt deck",
        "Abrir bandeja": "Open inbox",
        "Ver proyectos": "View projects",
        "Editar": "Edit",
        "Eliminar": "Delete",
        "Cancelar": "Cancel",
        "Guardar": "Save",
        "Elegir imagen": "Choose image",
        "Guardar receta": "Save recipe",
        "Iniciar flujo": "Start flow",
        "Eliminar paso": "Delete step",
        "Añadir paso": "Add step",
        "Guardar paso": "Save step",
        "Hecho": "Done",
        "Anterior": "Previous",
        "Archivar": "Archive",
        "Añadir desde la biblioteca": "Add from library",
        "Rechazar": "Reject",
        "Aprobar": "Approve",
        "Regenerar token": "Regenerate token",
        "Aprendizaje": "Learning",
        "Referencia": "Reference",
        "Nota": "Note",
        "Crear prompt": "Create prompt",
        "Bloques": "Blocks",
        "Título": "Title",
        "Etiquetas": "Tags",
        "URL (opcional)": "URL (optional)",
        "Título de la receta": "Recipe title",
        "Título del paso": "Step title",
        "¿Qué ocurre en este paso?": "What happens in this step?",
        "Prompt o plantilla de trabajo": "Prompt or working template",
        "Notas privadas": "Private notes",
        "Título del flujo": "Flow title",
        "¿Qué consigue este método?": "What does this method achieve?",
        "Título del proyecto": "Project title",
        "Resumen en una línea": "One-line summary",
        "Resumen": "Summary",
        "Dirección creativa": "Creative direction",
        "Restricciones": "Constraints",
        "Entregables": "Deliverables",
        "Recordar siempre": "Always remember",
        "Nombre": "Name",
        "Categoría": "Category",
        "Web (opcional)": "Website (optional)",
        "La uso para": "I use it for",
        "Funciona bien para": "Works well for",
        "Problemas habituales": "Common issues",
        "Por qué guardé esto": "Why I saved this",
        "URL original": "Original URL",
        "¿Por qué guardé esto?": "Why did I save this?",
        "Añadir atributo": "Add attribute",
        "Sin clasificar": "Unclassified",
        "Fijadas": "Pinned",
        "Filtros": "Filters",
        "Usar en LAB": "Use in LAB",
        "Borrar atributos": "Clear attributes",
        "Atributos visuales manuales": "Manual visual attributes",
        "Referencias del proyecto": "Project references",
        "Elige referencias existentes. Seguirán siendo elementos compartidos de la biblioteca.": "Choose existing references. They will remain shared library items.",
        "Aún no está conectada a ningún proyecto.": "Not connected to a project yet.",
        "Aún no hay experimentos conectados.": "No connected experiments yet.",
        "Aún no hay metadatos de herramientas.": "No tool metadata yet.",
        "La clasificación puede esperar. Conserva la fuente y el motivo.": "Classification can wait. Keep the source and the reason.",
        "campaña, verano, luz de producto": "campaign, summer, product lighting",
        "Crea primero un proyecto para conectar esta referencia.": "Create a project first to connect this reference.",
        "Fuente detectada": "Detected source",
        "Aplicación nativa": "Native app",
        "Estilo": "Style",
        "Medio": "Medium",
        "Sujeto": "Subject",
        "Iluminación": "Lighting",
        "Composición": "Composition",
        "Ambiente": "Mood",
        "Color": "Color",
        "Tipo": "Type",
        "Estado": "Status",
        "Herramienta": "Tool",
        "Proyecto": "Project",
        "Receta": "Recipe",
        "Experimento": "Experiment",
        "Decisión": "Decision",
        "Recurso": "Resource",
        "Idea": "Idea",
        "Memoria de trabajo": "Working memory",
        "Memoria canónica": "Canonical memory",
        "Resumen de sesión": "Session summary",
        "Nuevo": "New",
        "En pruebas": "Testing",
        "Funciona": "Works",
        "Canónico": "Canonical",
        "Evitar": "Avoid",
        "Archivado": "Archived",
        "Usuario": "User",
        "Otro agente": "Other agent",
        "Preparado": "Prepared",
        "Completado": "Completed",
        "Fallido": "Failed",
        "Sin valorar": "Unrated",
        "No funciona": "Does not work",
        "Interesante": "Interesting",
        "Mejor resultado": "Best result",
        "Conectada": "Connected",
        "Texto": "Text",
        "Número": "Number",
        "Booleano": "Boolean",
        "Opción": "Choice",
        "Guardar referencia": "Save reference",
        "Editar referencia": "Edit reference",
        "No hay imagen adjunta": "No image attached",
        "Imagen adjunta": "Image attached",
        "Buscar referencias, OCR y etiquetas…": "Search references, OCR and tags…",
        "Buscar referencias": "Search references",
        "Buscar en FIELD LAB": "Search FIELD LAB",
        "Cerrar captura rápida": "Close quick capture",
        "Añadir a Recopilar": "Add to Collect",
        "Abrir referencia": "Open reference",
        "Abrir original": "Open original",
        "Abrir web de la herramienta": "Open the tool website",
        "Fuente detectada: %@": "Detected source: %@",
        "Aún no hay clasificación creativa. Esta referencia aparecerá en Sin clasificar.": "There is no creative classification yet. This reference will appear under Unclassified.",
        "Enlazada a un proyecto": "Connected to a project",
        "General": "General",
        "Activar servidor MCP y abrir ajustes": "Start MCP server and open settings",
        "Abrir ajustes del servidor MCP": "Open MCP server settings",
        "Cerrar ajustes": "Close settings",
        "Iniciando": "Starting",
        "Detenido": "Stopped",
        "Activo": "Active",
        "Desactivado": "Disabled",
        "Idioma": "Language",
        "bloque": "block",
        "bloques": "blocks",
        "paso": "step",
        "pasos": "steps",
        "cambio": "change",
        "cambios": "changes",
        "captura": "capture",
        "capturas": "captures",
        "esperando ser ordenada": "waiting to be sorted",
        "esperando ser ordenadas": "waiting to be sorted",
        "Propuesta de": "Proposal from",
        "Puerto": "Port",
        "HTTP local protegido con token": "local HTTP protected with a token",
        "insertado": "inserted",
        "listos para combinar.": "ready to combine.",
        "Desfijar": "Unpin",
        "Fijar": "Pin",
        "Guardar cambios": "Save changes",
        "¿Qué has aprendido?": "What have you learned?",
        "Crear otra": "Create another",
        "Crea tu primer conjunto de lenguaje reutilizable.": "Create your first reusable prompt set.",
        "No hay nada esperando tu atención.": "Nothing is waiting for your attention.",
        "El puente local está activo.": "The local bridge is active.",
        "Conecta Claude, Codex y agentes compatibles en local.": "Connect Claude, Codex and compatible agents locally.",
        "Gestionar conexión": "Manage connection",
        "Configurar conexión": "Configure connection",
        "Aún no hay descripción": "No description yet",
        "Nuevo conocimiento": "New knowledge",
        "Editar conocimiento": "Edit knowledge",
        "luz, realismo": "light, realism",
        "Elige dos o más bloques para crear un conjunto reutilizable.": "Choose two or more blocks to create a reusable set.",
        "Editar paso": "Edit step",
        "Nuevo flujo": "New flow",
        "Editar flujo": "Edit flow",
        "Crear flujo": "Create flow",
        "Aún no hay instrucciones.": "No instructions yet.",
        "Copiado": "Copied",
        "Copiar plantilla": "Copy template",
        "Terminar": "Finish",
        "Siguiente": "Next",
        "Aún no escrito.": "Not written yet.",
        "Aún no escrita.": "Not written yet.",
        "Aún no escritas.": "Not written yet.",
        "Aún no escritos.": "Not written yet.",
        "Nuevo proyecto": "New project",
        "Editar proyecto": "Edit project",
        "Crear proyecto": "Create project",
        "Añadir herramienta": "Add tool",
        "Editar herramienta": "Edit tool",
        "Guardar herramienta": "Save tool",
        "Copiar": "Copy",
        "Ocultar": "Hide",
        "Mostrar": "Show",
        "Copiar configuración de Codex": "Copy Codex configuration",
        "Copiar configuración de Claude Code": "Copy Claude Code configuration",
        "Copiar prompt de configuración": "Copy setup prompt",
        "Prompt copiado": "Prompt copied",
        "Guardar en FIELD LAB": "Save to FIELD LAB",
        "Punto de conexión": "Endpoint",
        "Token local": "Local token",
        "Iniciar servidor": "Start server",
        "Detener servidor": "Stop server",
        "Esperando a que termine la selección de puerto…": "Waiting for port selection to finish…",
        "Inicia el servidor antes de copiar la configuración; el puerto definitivo aparece al activarse.": "Start the server before copying its configuration; the final port appears when it is active.",
        "Guardado en el Llavero de macOS. FIELD LAB y el helper son procesos distintos; macOS puede pedir permiso para cada uno la primera vez. Elige Permitir siempre si aparece.": "Saved in the macOS Keychain. FIELD LAB and the helper are separate processes; macOS may ask each one for permission the first time. Choose Always Allow if it appears.",
        "Guardado en el Llavero de macOS. Configura FIELD_MCP_TOKEN en el entorno del cliente MCP.": "Saved in the macOS Keychain. Set FIELD_MCP_TOKEN in the MCP client environment.",
        "Codex consulta el Llavero mediante un helper local; el token no queda en config.toml.": "Codex reads the token from the Keychain through a local helper; the token is not stored in config.toml.",
        "Codex lee FIELD_MCP_TOKEN del entorno del proceso. Reinícialo si acabas de configurar esa variable.": "Codex reads FIELD_MCP_TOKEN from the process environment. Restart it if you just set that variable.",
        "Claude Code consulta el Llavero mediante un helper local; verifica el estado con /mcp.": "Claude Code reads the token from the Keychain through a local helper; check the connection with /mcp.",
        "Claude Code expande FIELD_MCP_TOKEN en su configuración MCP. Comprueba la conexión con /mcp.": "Claude Code expands FIELD_MCP_TOKEN in its MCP settings. Check the connection with /mcp.",
        "Paso": "Step",
        "de": "of",
        "Copy Prompt & Open": "Copy Prompt & Open",
        "Agente": "Agent",
        "Bloque de prompt": "Prompt Block",
        "Flujo": "Flow",
        "Creado": "Created",
        "Importada": "Imported",
        "Análisis": "Analysis",
        "Dimensiones": "Dimensions",
        "Todas las fuentes": "All sources",
        "Abrir FIELD LAB": "Open FIELD LAB",
        "Iniciar servidor MCP": "Start MCP server",
        "Iniciar servidor MCP y abrir ajustes": "Start MCP server and open settings",
        "Referencia sin título": "Untitled reference",
        "Captura sin título": "Untitled capture",
        "Snapshot": "Snapshot",
        "Language": "Language",
        "Connections": "Connections",
        "Context": "Context",
        "Aún no hay flujos": "No flows yet",
        "Nada pendiente": "Nothing pending",
        "Nueva captura": "New capture",
        "Elige una propuesta": "Choose a proposal",
        "Revisa lo que un agente quiere conservar antes de convertirlo en memoria.": "Review what an agent wants to keep before turning it into memory.",
        "Acciones en FIELD LAB, nunca razonamiento privado.": "Actions in FIELD LAB, never private reasoning.",
        "La memoria permanente siempre pide confirmación.": "Permanent memory always requires confirmation.",
        "Bandeja": "Inbox",
        "Conexión de IA": "AI connection",
        "Contenedores de contexto para el trabajo que estás haciendo ahora.": "Context containers for the work you are doing now.",
        "Todo": "All",
        "Añadir": "Add",
        "Fuente": "Source",
        "Fuente detectada: ": "Detected source: ",
        "Guarda referencias, ideas y cosas que quieras volver a visitar.": "Save references, ideas and things you want to revisit.",
        "Guarda inspiración desde cualquier lugar": "Save inspiration from anywhere",
        "Trae una imagen, URL o nota desde Pinterest, Cosmos, Safari, Fotos, LinkedIn y más. La fuente queda vinculada para que la referencia siga siendo útil.": "Bring an image, URL or note from Pinterest, Cosmos, Safari, Photos, LinkedIn and more. Its source stays attached so the reference remains useful.",
        "Trae una imagen, URL o nota. Puedes clasificarla más tarde.": "Bring an image, URL or note. You can classify it later.",
        "Selecciona una imagen para ver su fuente, nota, atributos y conexiones de proyecto.": "Select an image to see its source, note, attributes and project connections.",
        "Elige una referencia": "Choose a reference",
        "Elige un experimento": "Choose an experiment",
        "Tu espacio de trabajo reúne referencias, prompts, herramientas y ajustes en ejecuciones reproducibles.": "Your Workbench is where references, prompts, tools and settings become reproducible Runs.",
        "Elige un elemento de conocimiento": "Choose a knowledge item",
        "Selecciona un elemento para leer su contexto completo y sus conexiones.": "Select an item to read its full context and connections.",
        "Selecciona el lenguaje que quieres llevar a tu próxima herramienta.": "Choose the language you want to take to your next tool.",
        "Tu método, documentado paso a paso, no automatizado.": "Your method, documented step by step, not automated.",
        "Contenedores de contexto, no tableros de tareas.": "Context containers, not task boards.",
        "Tu experiencia con las herramientas, no descripciones genéricas.": "Your experience with tools, not generic descriptions.",
        "Aún no hay nada aquí. Guarda un pequeño apunte para empezar a construir tu espacio de conocimiento.": "Nothing here yet. Capture a small piece of knowledge to start building your field.",
        "Un puente de memoria local para Claude, Codex y agentes compatibles.": "A local memory bridge for Claude, Codex and compatible agents.",
        "Capturas recientes": "Recent captures",
        "Tus últimas notas aparecerán aquí.": "Your latest notes will appear here.",
        "Capturar algo": "Capture something",
        "Elige algo para reutilizar": "Choose something to reuse",
        "Lee cada elemento en su contexto completo.": "Read each item in its complete context.",
        "Tu bandeja está despejada": "Inbox is clear",
        "Empieza a construir tu campo": "Start building your field",
        "Las nuevas capturas y notas de trabajo esperarán aquí hasta que estés listo para organizarlas.": "New captures and working notes wait here until you are ready to organize them.",
        "Atributos visuales": "Visual attributes",
        "Experimentos relacionados": "Related experiments",
        "Metadatos": "Metadata",
        "Procedencia": "Origin",
        "Conjunto de prompts": "Prompt set",
        "Conocimiento del proyecto": "Project knowledge",
        "Conocimiento conectado": "Connected knowledge",
        "Conectar Codex": "Connect Codex",
        "Conectar Claude Code": "Connect Claude Code",
        "Configurar con una IA": "Set up with an AI",
        "Permisos": "Permissions",
        "Leer conocimiento": "Read knowledge",
        "Buscar conocimiento": "Search knowledge",
        "Añadir memoria de trabajo": "Add working memory",
        "Proponer memoria permanente": "Propose permanent memory",
        "Escrituras canónicas directas": "Direct canonical writes",
        "Eliminar conocimiento": "Delete knowledge",
        "ORIENTACIÓN RELACIONADA": "RELATED GUIDANCE",
        "No references yet": "No references yet",
        "Save visual material in Collect first.": "Save visual material in Collect first.",
        "Aquí se reúne el conocimiento que puedes reutilizar.": "Your reusable knowledge lives here",
        "Las conclusiones se convierten en aprendizajes, recetas y bloques de prompt.": "Conclusions become Learnings, Recipes and Prompt Blocks.",
        "Aún no hay instantáneas": "No snapshots yet",
        "La configuración que estás probando": "The setup you are testing",
        "Elige el resultado del que más puedas aprender": "Select the result that teaches you the most",
        "Añade resultados a dos ejecuciones como mínimo para compararlas": "Add results to at least two Runs to compare",
        "Crear un proyecto": "Create a project",
        "Nuevo paso": "New step",
        "Elige un flujo": "Choose a flow",
        "Un flujo te ayuda a repetir lo que ya funciona.": "A flow helps you repeat what already works.",
        "Elige un proyecto": "Choose a project",
        "Un proyecto ofrece a los agentes un paquete de contexto compacto y duradero.": "A project gives agents a compact, lasting context package.",
        "Elige una herramienta": "Choose a tool",
        "La página de una herramienta reúne el conocimiento acumulado sobre cómo funciona para ti.": "A tool page gathers what you have learned about how it works for you.",
        "Todo el conocimiento": "All knowledge",
        "Añadir referencia": "Add reference",
        "Importar referencia": "Import reference",
        "Aún no hay pasos": "No steps yet",
        "No hay pasos": "No steps",
        "Aún no hay referencias": "No references yet",
        "Primero guarda material visual en Recopilar.": "Save visual material in Collect first.",
        "BLOQUES": "BLOCKS",
        "INGREDIENTS": "INGREDIENTS",
        "ARTÍCULOS": "ITEMS",
        "EJECUCIONES": "RUNS",
        "COMPARAR": "COMPARE",
        "REFERENCIAS": "REFERENCES",
        "PROMPT": "PROMPT",
        "HERRAMIENTA": "TOOL",
        "AJUSTES": "SETTINGS",
        "CONCLUSIÓN": "CONCLUSION",
        "Captura": "Capture",
        "elemento": "item",
        "elementos": "items",
        "Externa": "External",
        "Duplicado de": "Duplicated from",
        "Cambios respecto a": "Changed from",
        "waiting to be sorted": "waiting to be sorted",
        "Buscar en FIELD": "Search FIELD",
        "Crear en FIELD": "Create in FIELD",
        "Buscar": "Search",
        "Colección": "Collection",
        "Contexto": "Context",
        "proyectos": "projects",
        "Archivada": "Archived",
        "Unidad": "Unit",
        "Fijada": "Pinned",
        "Origen": "Source",
        "Experimentos": "Experiments",
        "Buscar experimentos": "Search experiments",
        "Prompt": "Prompt",
        "Actualizado": "Updated",
        "Modelo": "Model",
        "Conocimiento": "Knowledge",
        "Enlace": "Link",
        "Guardado": "Saved",
        "Prompts": "Prompts",
        "Manual": "Manual",
        "Restaurar referencia": "Restore reference",
        "Archivar referencia": "Archive reference",
        "Quitar de fijados": "Unpin",
        "Busca en FIELD": "Search in FIELD",
        "Activas": "Active",
        "Activos": "Active",
        "Archivadas": "Archived",
        "Archivados": "Archived",
        "No hay referencias archivadas": "No archived references",
        "Tu colección empieza aquí": "Your collection starts here",
        "No hay referencias que coincidan con la búsqueda.": "No references match your search.",
        "Las referencias archivadas aparecerán aquí y podrás restaurarlas cuando quieras.": "Archived references will appear here, where you can restore them.",
        "Guarda imágenes, enlaces e ideas que quieras volver a encontrar. También puedes enviar contenido desde el menú Compartir de otras apps.": "Save images, links and ideas you want to find again. You can also share content here from other apps.",
        "Guardar una referencia": "Save a reference",
        "Sin título": "Untitled",
        "Imagen de referencia": "Reference image",
        "Añadida": "Added",
        "Quitar de fijadas": "Unpin",
        "Fijar referencia": "Pin reference",
        "Más opciones": "More options",
        "Aceptar": "OK",
        "Inténtalo de nuevo.": "Please try again.",
        "¿Eliminar esta referencia?": "Delete this reference?",
        "Eliminar referencia": "Delete reference",
        "Esta acción no se puede deshacer.": "This action can't be undone.",
        "No hay experimentos archivados": "No archived experiments",
        "Prueba una idea": "Try an idea",
        "No hay experimentos que coincidan con la búsqueda.": "No experiments match your search.",
        "Los experimentos archivados aparecerán aquí. Puedes restaurarlos desde Editar.": "Archived experiments will appear here. Restore them from Edit.",
        "El Laboratorio guarda tus experimentos y conclusiones junto a la biblioteca.": "Lab keeps your experiments and conclusions with your library.",
        "Crear experimento": "Create experiment",
        "Objetivo": "Goal",
        "Añade el propósito de esta prueba.": "Add the purpose of this experiment.",
        "Configuración": "Setup",
        "Compartir prompt": "Share prompt",
        "Conclusión": "Conclusion",
        "Aún no hay resultados. Crea un run para guardar una copia del prompt y empezar a anotar el resultado.": "No results yet. Create a Run to save a copy of the prompt and start recording its result.",
        "Crear run": "Create Run",
        "Reutilizar": "Reuse",
        "Guardar conclusión como aprendizaje": "Save conclusion as a Learning",
        "Guardar mejor run como receta": "Save best Run as a Recipe",
        "Eliminar experimento": "Delete experiment",
        "Opciones del experimento": "Experiment options",
        "¿Eliminar este experimento?": "Delete this experiment?",
        "También se eliminarán sus runs. Esta acción no se puede deshacer.": "Its Runs will also be deleted. This action can't be undone.",
        "Resultado": "Result",
        "Nombre del run": "Run name",
        "Evaluación": "Evaluation",
        "Observaciones": "Observations",
        "Prompt guardado": "Saved prompt",
        "Este run no tiene un prompt guardado.": "This Run has no saved prompt.",
        "Configuración del run": "Run setup",
        "Imagen del resultado": "Result image",
        "Eliminar run": "Delete Run",
        "Opciones del run": "Run options",
        "¿Eliminar este run?": "Delete this Run?",
        "No se encontró el experimento de este run.": "The experiment for this Run could not be found.",
        "Ejecución": "Run",
        "Una referencia vinculada ya no está disponible.": "A linked reference is no longer available.",
        "Un bloque de prompt vinculado ya no está disponible.": "A linked Prompt Block is no longer available.",
        "Tipo de conocimiento": "Knowledge type",
        "No hay conocimiento archivado": "No archived knowledge",
        "Lo que sabes, a mano": "What you know, close at hand",
        "No hay elementos que coincidan con la búsqueda.": "No items match your search.",
        "Los elementos archivados aparecerán aquí y podrás restaurarlos desde Editar.": "Archived items will appear here. Restore them from Edit.",
        "Los elementos archivados aparecerán aquí. Puedes restaurarlos desde Editar.": "Archived items will appear here. You can restore them from Edit.",
        "Guarda aprendizajes, recetas y bloques de prompt para reutilizarlos.": "Save Learnings, Recipes and Prompt Blocks to reuse them.",
        "Guardar conocimiento": "Save knowledge",
        "Sin contenido adicional.": "No additional content.",
        "Usar esta receta": "Use this Recipe",
        "Esta receta todavía no tiene un prompt.": "This Recipe doesn't have a prompt yet.",
        "¿Eliminar este elemento?": "Delete this item?",
        "Busca en tu memoria creativa": "Search your creative memory",
        "Referencias, experimentos, aprendizajes, recetas y bloques de prompt.": "References, experiments, Learnings, Recipes and Prompt Blocks.",
        "Referencia no disponible": "Reference unavailable",
        "Elemento no disponible": "Item unavailable",
        "Experimento no disponible": "Experiment unavailable",
        "Nueva referencia": "New reference",
        "Nuevo aprendizaje": "New Learning",
        "Nuevo bloque de prompt": "New Prompt Block",
        "Nueva": "New",
        "Experimento desde receta": "Experiment from Recipe",
        "Editar experimento": "Edit experiment",
        "¿Qué quieres recordar?": "What do you want to remember?",
        "Nombre del bloque": "Block name",
        "Nombre de la receta": "Recipe name",
        "Nombre de la prueba": "Experiment name",
        "Añade una nota para explicar por qué te interesa…": "Add a note about why this matters to you…",
        "Escribe el prompt de la receta…": "Write the Recipe prompt…",
        "Escribe los detalles que quieras conservar…": "Write down the details you want to keep…",
        "¿Qué quieres probar?": "What do you want to try?",
        "Cargando imagen…": "Loading image…",
        "Añadir imagen": "Add image",
        "Cambiar imagen": "Change image",
        "Pega un enlace": "Paste a link",
        "No se pudo leer la imagen seleccionada.": "The selected image couldn't be read.",
        "Preparando imagen": "Preparing image",
        "Imagen preparada": "Image ready",
        "Quitar imagen": "Remove image",
        "Enlace (opcional)": "Link (optional)",
        "Una receta necesita un prompt para poder crear un experimento.": "A Recipe needs a prompt before you can create an experiment from it.",
        "Etiquetas, separadas por comas": "Tags, separated by commas",
        "Prompt (opcional)": "Prompt (optional)",
        "Sin proyecto": "No project",
        "Modelo (opcional)": "Model (optional)",
        "Configuración de cada run": "Settings for each Run",
        "Al añadir un bloque, su texto se suma al prompt. Quitar el vínculo conserva el texto insertado.": "Adding a block appends its text to the prompt. Removing the link keeps the inserted text.",
        "Guarda referencias desde Recopilar para vincularlas aquí.": "Save references in Collect to link them here.",
        "Crea bloques de prompt desde Aprender para vincularlos aquí.": "Create Prompt Blocks in Learn to link them here.",
        "Añade parámetros que quieras conservar en cada resultado.": "Add settings you want to keep with each result.",
        "Prueba de la receta «%@».": "Experiment from the Recipe “%@”.",
        "Parámetro": "Setting",
        "Valor": "Value",
        "Eliminar ajuste": "Remove setting",
        "Añadir ajuste": "Add setting",
        "Ninguno": "None",
        "Ninguna": "None",
        "seleccionado": "selected",
        "seleccionados": "selected",
        "seleccionada": "selected",
        "seleccionadas": "selected",
        "REFERENCIA": "REFERENCE",
        "CONOCIMIENTO": "KNOWLEDGE",
        "LABORATORIO": "LAB",
        "Tus datos": "Your data",
        "Biblioteca local disponible sin conexión": "Your local library is available offline",
        "Cuenta iCloud disponible": "iCloud account available",
        "Sincronización iCloud pendiente": "iCloud sync pending",
        "Guardar desde el menú Compartir": "Save from the Share menu",
        "Compartir pendiente de configuración": "Share extension setup pending",
        "Compartir con FIELD": "Share with FIELD",
        "Revisar importaciones": "Check imports",
        "Configuración pendiente": "Setup pending",
        "Comprobar ahora": "Check now",
        "Copia Apps/Config/FieldICloud.local.xcconfig.example como FieldICloud.local.xcconfig, sustituye los IDs de ejemplo y activa iCloud + CloudKit en los targets de iPhone y Mac. La biblioteca local seguirá disponible mientras tanto.": "Copy Apps/Config/FieldICloud.local.xcconfig.example to FieldICloud.local.xcconfig, replace the sample IDs and enable iCloud + CloudKit for the iPhone and Mac targets. Your local library remains available in the meantime.",
        "Para importar desde Compartir, registra FIELD_APP_GROUP_ID y activa el mismo App Group en la app de iPhone y en FIELDShare.": "To import from Share, set FIELD_APP_GROUP_ID and enable the same App Group for the iPhone app and FIELDShare.",
        "%d referencias importadas desde Compartir": "%d references imported from Share",
        "FIELD ha abierto la biblioteca local. iCloud no se pudo iniciar: %@": "FIELD opened its local library. iCloud couldn't start: %@",
        "No se pudieron importar las referencias compartidas: %@": "Shared references couldn't be imported: %@",
        "Añade el contenedor iCloud de tu equipo en la configuración del proyecto.": "Add your team's iCloud container in the project settings.",
        "La cuenta iCloud está disponible. FIELD conserva los cambios en el iPhone sin conexión y los envía a CloudKit en segundo plano cuando puede.": "Your iCloud account is available. FIELD keeps iPhone changes offline and syncs them to CloudKit in the background when possible.",
        "Inicia sesión en iCloud desde Ajustes del iPhone para sincronizar FIELD.": "Sign in to iCloud in iPhone Settings to sync FIELD.",
        "Este dispositivo tiene restringido el acceso a iCloud.": "This device is restricted from accessing iCloud.",
        "No se pudo comprobar el estado de iCloud.": "Couldn't check iCloud status.",
        "Comprobando iCloud": "Checking iCloud",
        "Inicia sesión en iCloud": "Sign in to iCloud",
        "iCloud restringido": "iCloud restricted",
        "iCloud no disponible": "iCloud unavailable",
        "Falta configurar iCloud": "iCloud setup required",
        "Referencias · %d": "References · %d",
        "Experimentos · %d": "Experiments · %d",
        "Resultados · %d": "Results · %d",
        "Conocimiento · %d": "Knowledge · %d",
        "Imagen de %@": "Image of %@",
        "Imagen del resultado de %@": "Result image for %@",
        "No se pudo actualizar la referencia: %@": "Couldn't update reference: %@",
        "No se pudo actualizar el elemento: %@": "Couldn't update item: %@",
        "No se pudo completar la acción": "Couldn't complete the action",
        "No se pudo eliminar la referencia: %@": "Couldn't delete reference: %@",
        "No se pudo crear el run: %@": "Couldn't create Run: %@",
        "No se pudo guardar el aprendizaje: %@": "Couldn't save Learning: %@",
        "No se pudo guardar la receta: %@": "Couldn't save Recipe: %@",
        "No se pudo eliminar el experimento: %@": "Couldn't delete experiment: %@",
        "No se pudo cargar la imagen: %@": "Couldn't load image: %@",
        "No se pudo guardar: %@": "Couldn't save: %@",
        "No se pudo eliminar el elemento: %@": "Couldn't delete item: %@",
        "No se pudo eliminar el run: %@": "Couldn't delete Run: %@",
        "%d referencias vinculadas ya no están disponibles.": "%d linked references are no longer available.",
        "%d bloques de prompt vinculados ya no están disponibles.": "%d linked Prompt Blocks are no longer available.",
        "No se pudo guardar en FIELD": "Couldn't save to FIELD",
        "Guardando en FIELD…": "Saving to FIELD…",
        "Guardado. Abre FIELD para verlo en Recopilar.": "Saved. Open FIELD to see it in Collect.",
        "Cerrar": "Close",
        "Esta app no ha compartido una imagen, un enlace ni texto compatible.": "This app didn't share a supported image, link or text.",
        "No se pudo leer el contenido compartido.": "Couldn't read the shared content.",
        "Falta configurar el grupo compartido de FIELD en Xcode.": "Configure FIELD's shared App Group in Xcode.",
        "No se pudo guardar la referencia: %@": "Couldn't save reference: %@",
    ]

    static var currentLanguage: FieldLanguage {
        let groupID = Bundle.main.object(forInfoDictionaryKey: "FIELD_APP_GROUP_ID") as? String
        let sharedLanguage = groupID.flatMap { UserDefaults(suiteName: $0) }?.string(forKey: FieldLanguage.preferenceKey)
        let standardLanguage = UserDefaults.standard.string(forKey: FieldLanguage.preferenceKey)
        let storedLanguage = Bundle.main.object(forInfoDictionaryKey: "NSExtension") == nil
            ? standardLanguage ?? sharedLanguage
            : sharedLanguage ?? standardLanguage
        return FieldLanguage(
            rawValue: storedLanguage ?? FieldLanguage.spanish.rawValue
        ) ?? .spanish
    }

    static func text(_ source: String, language: FieldLanguage? = nil) -> String {
        let selectedLanguage = language ?? currentLanguage

        return switch selectedLanguage {
        case .spanish: spanish[source] ?? source
        case .english: english[source] ?? source
        }
    }

    static func format(_ source: String, _ arguments: CVarArg...) -> String {
        String(format: text(source), locale: currentLanguage.locale, arguments: arguments)
    }

    static func pluralized(_ count: Int, singular: String, plural: String) -> String {
        "\(count) \(text(count == 1 ? singular : plural))"
    }

    static func blockInsertion(_ count: Int) -> String {
        switch currentLanguage {
        case .spanish:
            "\(count) bloque\(count == 1 ? "" : "s") insertado\(count == 1 ? "" : "s")"
        case .english:
            "\(count) block\(count == 1 ? "" : "s") inserted"
        }
    }

    static func blocksReadyToCombine(_ count: Int) -> String {
        switch currentLanguage {
        case .spanish:
            "\(count) bloque\(count == 1 ? "" : "s") listo\(count == 1 ? "" : "s") para combinar."
        case .english:
            "\(count) prompt block\(count == 1 ? "" : "s") ready to combine."
        }
    }

    static func inboxStatus(_ count: Int) -> String {
        switch currentLanguage {
        case .spanish:
            "\(count) captura\(count == 1 ? "" : "s") esperando ser ordenada\(count == 1 ? "" : "s")."
        case .english:
            "\(count) capture\(count == 1 ? "" : "s") waiting to be sorted."
        }
    }

    static func stepProgress(current: Int, total: Int) -> String {
        "\(text("Step")) \(current) \(text("of")) \(total)"
    }

    static func runName(_ order: Int) -> String {
        switch currentLanguage {
        case .spanish: "Ejecución \(order)"
        case .english: "Run \(order)"
        }
    }

    static func snapshotCount(_ count: Int) -> String {
        switch currentLanguage {
        case .spanish:
            "\(count) instantánea\(count == 1 ? "" : "s") de configuración"
        case .english:
            "\(count) setup snapshot\(count == 1 ? "" : "s")"
        }
    }

    static func reuseReferencePrompt(_ title: String) -> String {
        switch currentLanguage {
        case .spanish: "Reutiliza «\(title)» en una configuración existente o empieza una nueva."
        case .english: "Reuse “\(title)” in an existing setup or start a new one."
        }
    }

    static func referenceAnalysisState(_ rawValue: String) -> String {
        switch rawValue {
        case "pending": text("Pending")
        case "processing": text("Processing")
        case "complete": text("Complete")
        case "failed": text("Failed")
        case "notAvailable": text("Not available")
        default: rawValue.capitalized
        }
    }

    static func activityAction(_ rawValue: String) -> String {
        switch rawValue {
        case "read_resource": return text("Read resource")
        case "searched_knowledge": return text("Searched knowledge")
        case "searched_references": return text("Searched references")
        case "read_reference": return text("Read reference")
        case "read_project_context": return text("Read project context")
        case "read_project_constraints": return text("Read project constraints")
        case "read_tool_knowledge": return text("Read tool knowledge")
        case "read_project_decisions": return text("Read project decisions")
        case "read_experiment": return text("Read experiment")
        case "list_experiment_runs": return text("Listed experiment runs")
        case "compare_runs_metadata": return text("Compared run metadata")
        case "search_experiments": return text("Searched experiments")
        case "read_best_run": return text("Read best run")
        case "read_recipe": return text("Read recipe")
        case "read_workflow": return text("Read workflow")
        case "proposed_reference_tags": return text("Proposed reference tags")
        case "approved_reference_tags": return text("Approved reference tags")
        case "rejected_proposal": return text("Rejected proposal")
        case "added_working_note": return text("Added working note")
        case "saved_session_summary": return text("Saved session summary")
        default:
            if rawValue.hasPrefix("proposed_") || rawValue.hasPrefix("approved_") {
                let prefix = rawValue.hasPrefix("proposed_") ? "proposed_" : "approved_"
                let kind = String(rawValue.dropFirst(prefix.count))
                let kindName = switch kind {
                case "promptBlock": "Prompt Block"
                case "learning": "Learning"
                case "recipe": "Recipe"
                case "decision": "Decision"
                case "reference": "Reference"
                case "style": "Style"
                case "experiment": "Experiment"
                case "note": "Note"
                case "resource": "Resource"
                case "idea": "Idea"
                case "workingMemory": "Working memory"
                case "canonicalMemory": "Canonical memory"
                case "sessionSummary": "Session summary"
                case "flow": "Flow"
                default: kind.capitalized
                }
                return "\(text(prefix == "proposed_" ? "Proposed" : "Approved")) \(text(kindName))"
            }
            return rawValue.replacingOccurrences(of: "_", with: " ").capitalized
        }
    }

    static func portDescription(_ port: UInt16) -> String {
        "\(text("Port")) \(port) · \(text("HTTP local protegido con token"))"
    }

    static func copiedDescription(_ item: String) -> String {
        switch currentLanguage {
        case .spanish: "\(item) copiado"
        case .english: "\(item) copied"
        }
    }
}

typealias L10n = FieldLocalization
