#!/usr/bin/env python3
"""Assign local FIELD ports and data stores to Codex-created Git worktrees."""

from __future__ import annotations

import argparse
import contextlib
import datetime as dt
import fcntl
import hashlib
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Iterator


FIRST_PORT = 8765
LAST_PORT = 8800
BRANCH_PREFIX = "task/"
METADATA_NAME = ".field-worktree.json"
ENV_NAME = ".field-worktree.env"


def git(repo: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        ["git", "-C", str(repo), *args],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if check and result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip() or "Git command failed.")
    return result


def worktree_records(repo: Path) -> list[dict[str, str]]:
    result = git(repo, "worktree", "list", "--porcelain")
    records: list[dict[str, str]] = []
    current: dict[str, str] = {}
    for line in result.stdout.splitlines() + [""]:
        if not line:
            if current:
                records.append(current)
                current = {}
            continue
        key, _, value = line.partition(" ")
        current[key] = value
    return records


def repo_context() -> tuple[Path, Path, Path]:
    current = Path(git(Path.cwd(), "rev-parse", "--show-toplevel").stdout.strip()).resolve()
    records = worktree_records(current)
    main = next(
        (Path(record["worktree"]).resolve() for record in records if record.get("branch") == "refs/heads/main"),
        None,
    )
    if main is None:
        if git(current, "branch", "--show-current").stdout.strip() != "main":
            raise RuntimeError("Could not find FIELD's local main worktree.")
        main = current
    common_dir = Path(git(current, "rev-parse", "--path-format=absolute", "--git-common-dir").stdout.strip()).resolve()
    return current, main, common_dir


def metadata_path(worktree: Path) -> Path:
    return worktree / METADATA_NAME


def read_metadata(worktree: Path) -> dict[str, object]:
    path = metadata_path(worktree)
    if not path.is_file():
        return {}
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
        return value if isinstance(value, dict) else {}
    except (OSError, json.JSONDecodeError) as error:
        raise RuntimeError(f"Cannot read {path}: {error}") from error


def write_local_file(path: Path, contents: str) -> None:
    temp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as handle:
            handle.write(contents)
            temp_path = Path(handle.name)
        os.replace(temp_path, path)
    finally:
        if temp_path is not None and temp_path.exists():
            temp_path.unlink()


def write_metadata(worktree: Path, value: dict[str, object]) -> None:
    write_local_file(metadata_path(worktree), json.dumps(value, indent=2, sort_keys=True) + "\n")


def write_env_file(worktree: Path, port: int, data_directory: Path) -> None:
    contents = (
        "# Generated by scripts/worktree.py. Do not commit this file.\n"
        f"FIELD_MCP_PORT={port}\n"
        f"FIELD_DATA_DIR={shlex.quote(str(data_directory))}\n"
    )
    write_local_file(worktree / ENV_NAME, contents)


@contextlib.contextmanager
def port_pool_lock(common_dir: Path) -> Iterator[None]:
    repo_key = hashlib.sha256(str(common_dir).encode("utf-8")).hexdigest()[:16]
    lock_path = Path(tempfile.gettempdir()) / f"field-worktree-ports-{repo_key}.lock"
    with lock_path.open("a+") as lock_file:
        fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX)
        yield


def port_is_busy(port: int) -> bool:
    lsof = shutil.which("lsof")
    if not lsof:
        raise RuntimeError("Cannot inspect local ports because 'lsof' is unavailable.")
    result = subprocess.run(
        [lsof, "-nP", "-t", f"-iTCP:{port}", "-sTCP:LISTEN"],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.returncode == 0:
        return bool(result.stdout.strip())
    if result.returncode == 1 and not result.stderr.strip():
        return False
    raise RuntimeError(result.stderr.strip() or f"Could not inspect TCP port {port} with lsof.")


def slug_from_branch(branch: str) -> str | None:
    return branch.removeprefix(BRANCH_PREFIX) if branch.startswith(BRANCH_PREFIX) else None


def cmd_register(requested_slug: str | None) -> None:
    current, main, common_dir = repo_context()
    if current == main:
        raise RuntimeError("Open this task in a Codex-created worktree first; do not register the main checkout.")

    branch = git(current, "branch", "--show-current").stdout.strip()
    slug = slug_from_branch(branch)
    if slug is None:
        raise RuntimeError(
            "This Codex worktree has no task/<slug> branch. In the task header, use 'Create branch here' "
            "with a name such as task/reference-search, then run register."
        )
    if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", slug):
        raise RuntimeError(f"Invalid task branch slug: {slug!r}.")
    if requested_slug and requested_slug != slug:
        raise RuntimeError(f"Current branch is {branch}; register it with slug '{slug}'.")

    data_directory = Path.home() / "Library" / "Application Support" / "Field LAB" / "worktrees" / slug
    now = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")

    with port_pool_lock(common_dir):
        # Read under the same lock as assignment. Otherwise two simultaneous
        # registrations can both see a stale worktree list and claim one port.
        records = worktree_records(main)
        old_metadata = read_metadata(current)
        used_ports: set[int] = set()
        for record in records:
            other_path = Path(record["worktree"]).resolve()
            if other_path == current:
                continue
            metadata = read_metadata(other_path)
            if "port" in metadata:
                used_ports.add(int(metadata["port"]))

        old_port = int(old_metadata.get("port", 0))
        if FIRST_PORT <= old_port <= LAST_PORT and old_port not in used_ports:
            port = old_port
        else:
            port = next((p for p in range(FIRST_PORT, LAST_PORT + 1) if p not in used_ports and not port_is_busy(p)), None)
        if port is None:
            raise RuntimeError(
                f"No free MCP port remains in {FIRST_PORT}-{LAST_PORT}. Stop unrelated listeners. "
                "To release a reservation, archive its completed Codex task; this manager does not delete worktrees."
            )

        write_env_file(current, port, data_directory)
        write_metadata(current, {
            "version": 1,
            "slug": slug,
            "branch": branch,
            "path": str(current),
            "port": port,
            "data_directory": str(data_directory),
            "active": True,
            "created_at": str(old_metadata.get("created_at", now)),
            "last_seen_at": now,
        })

    print(f"Registered Codex worktree: {current}")
    print(f"Branch: {branch}")
    print(f"MCP port: {port}")
    print(f"Isolated SwiftData store: {data_directory}")


def find_worktree(main: Path, registry_slug: str, current: Path) -> tuple[str, Path, dict[str, object]]:
    for record in worktree_records(main):
        path = Path(record["worktree"]).resolve()
        branch = record.get("branch", "detached").removeprefix("refs/heads/")
        metadata = read_metadata(path)
        slug = str(metadata.get("slug") or slug_from_branch(branch) or "")
        if slug == registry_slug:
            if not metadata:
                raise RuntimeError(f"Codex worktree '{branch}' is not registered. Run register from inside that worktree.")
            return branch, path, metadata
        if path == current.resolve() and slug:
            return branch, path, metadata
    raise RuntimeError(f"No Codex worktree found for slug '{registry_slug}'.")


def resolve_target(requested_slug: str | None, current: Path, main: Path) -> tuple[str, Path, dict[str, object]]:
    if requested_slug:
        return find_worktree(main, requested_slug, current)
    if current == main:
        raise RuntimeError("Pass a task slug when running this command from main.")
    branch = git(current, "branch", "--show-current").stdout.strip()
    metadata = read_metadata(current)
    slug = str(metadata.get("slug") or slug_from_branch(branch) or "")
    if not slug or not metadata:
        raise RuntimeError("This Codex worktree is not registered. Run 'python3 scripts/worktree.py register' first.")
    return branch, current, metadata


def cmd_list() -> None:
    _, main, _ = repo_context()
    assigned_ports: set[int] = set()
    available_ports = 0
    for record in worktree_records(main):
        path = Path(record["worktree"]).resolve()
        if path == main:
            continue
        branch = record.get("branch", "detached").removeprefix("refs/heads/")
        metadata = read_metadata(path)
        if metadata:
            port = int(metadata.get("port", 0))
            assigned_ports.add(port)
            activity = "active" if metadata.get("active", True) else "inactive"
            listener = "busy" if port and port_is_busy(port) else "free"
            print(f"{branch:36} {port:5} {activity:8} port-{listener:4} registered  {path}")
        else:
            print(f"{branch:36} {'-':5} {'-':8} {'-':9} unregistered {path}")
    for port in range(FIRST_PORT, LAST_PORT + 1):
        if port not in assigned_ports and not port_is_busy(port):
            available_ports += 1
    print(f"Available unassigned MCP ports: {available_ports} of {LAST_PORT - FIRST_PORT + 1}.")
    if available_ports == 0:
        print("Stop unrelated listeners. To release a reservation, archive its completed task in Codex; Codex owns worktree cleanup.")


def cmd_mark_active(requested_slug: str | None, active: bool) -> None:
    current, main, _ = repo_context()
    branch, path, metadata = resolve_target(requested_slug, current, main)
    metadata["active"] = active
    metadata["last_seen_at"] = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")
    write_metadata(path, metadata)
    print(f"Marked {branch} {'active' if active else 'inactive'}.")


def cmd_start(requested_slug: str | None) -> int:
    current, main, _ = repo_context()
    branch, path, metadata = resolve_target(requested_slug, current, main)
    metadata["active"] = True
    metadata["last_seen_at"] = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")
    write_metadata(path, metadata)

    environment = os.environ.copy()
    environment["FIELD_MCP_PORT"] = str(metadata["port"])
    environment["FIELD_DATA_DIR"] = str(metadata["data_directory"])
    print(f"Starting {branch} on http://127.0.0.1:{metadata['port']}/mcp (Ctrl-C to stop)", flush=True)
    return subprocess.call(["swift", "run", "FIELD"], cwd=path, env=environment)


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description="Assign ports and isolated stores to Codex-created FIELD worktrees.")
    commands = result.add_subparsers(dest="command", required=True)

    register = commands.add_parser("register", help="assign a port and isolated store to the current Codex worktree")
    register.add_argument("slug", nargs="?", help="optional check that the current task branch has this slug")

    commands.add_parser("list", help="show Codex Git worktrees, port assignments, and activity markers")

    start = commands.add_parser("start", help="run FIELD with this worktree's port and data directory")
    start.add_argument("slug", nargs="?")

    activate = commands.add_parser("activate", help="mark this worktree active while its Codex task is in use")
    activate.add_argument("slug", nargs="?")

    deactivate = commands.add_parser("deactivate", help="mark a closed or paused worktree inactive")
    deactivate.add_argument("slug", nargs="?")

    return result


def main() -> int:
    args = parser().parse_args()
    try:
        if args.command == "register":
            cmd_register(args.slug)
            return 0
        if args.command == "list":
            cmd_list()
            return 0
        if args.command == "start":
            return cmd_start(args.slug)
        if args.command == "activate":
            cmd_mark_active(args.slug, True)
            return 0
        if args.command == "deactivate":
            cmd_mark_active(args.slug, False)
            return 0
    except (EOFError, OSError, RuntimeError, ValueError) as error:
        print(f"worktree: {error}", file=sys.stderr)
        return 1
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
