#!/usr/bin/env python3
"""Manage local FIELD worktrees, their ports, and isolated development stores."""

from __future__ import annotations

import argparse
import contextlib
import datetime as dt
import fcntl
import json
import os
import re
import shlex
import socket
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Iterator


FIRST_PORT = 8765
LAST_PORT = 8800
BRANCH_PREFIX = "task/"


def git(repo: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        ["git", "-C", str(repo), *args],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if check and result.returncode != 0:
        message = result.stderr.strip() or result.stdout.strip() or "Git command failed."
        raise RuntimeError(message)
    return result


def worktree_records(repo: Path) -> list[dict[str, str]]:
    result = git(repo, "worktree", "list", "--porcelain")
    records: list[dict[str, str]] = []
    current: dict[str, str] = {}
    for line in result.stdout.splitlines() + [""]:
        if not line:
            if current:
                records.append(current)
                current = {}
            continue
        key, _, value = line.partition(" ")
        current[key] = value
    return records


def project_roots() -> tuple[Path, Path]:
    this_checkout = Path(__file__).resolve().parent.parent
    records = worktree_records(this_checkout)
    main_root = next(
        (Path(record["worktree"]).resolve() for record in records if record.get("branch") == "refs/heads/main"),
        None,
    )
    if main_root is None:
        branch = git(this_checkout, "branch", "--show-current").stdout.strip()
        if branch != "main":
            raise RuntimeError("Could not find the local main worktree.")
        main_root = this_checkout
    worktree_home = main_root.parent / "FIELD-worktrees"
    return main_root, worktree_home


def registry_paths(worktree_home: Path) -> tuple[Path, Path]:
    return worktree_home / ".field-worktrees.json", worktree_home / ".field-worktrees.lock"


def read_registry(path: Path) -> dict[str, dict[str, object]]:
    if not path.exists():
        return {}
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
        return value if isinstance(value, dict) else {}
    except (OSError, json.JSONDecodeError) as error:
        raise RuntimeError(f"Cannot read worktree registry {path}: {error}") from error


def write_registry(path: Path, registry: dict[str, dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as handle:
        json.dump(registry, handle, indent=2, sort_keys=True)
        handle.write("\n")
        temp_path = Path(handle.name)
    os.replace(temp_path, path)


@contextlib.contextmanager
def locked_registry(worktree_home: Path) -> Iterator[tuple[Path, dict[str, dict[str, object]]]]:
    worktree_home.mkdir(parents=True, exist_ok=True)
    registry_path, lock_path = registry_paths(worktree_home)
    with lock_path.open("a+") as lock_file:
        fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX)
        registry = read_registry(registry_path)
        yield registry_path, registry


def port_is_busy(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as candidate:
        try:
            candidate.bind(("127.0.0.1", port))
        except OSError:
            return True
    return False


def worktree_is_clean(path: Path) -> bool:
    return not git(path, "status", "--porcelain").stdout.strip()


def path_is_current(path: Path) -> bool:
    try:
        Path.cwd().resolve().relative_to(path.resolve())
        return True
    except ValueError:
        return False


def resolve_slug(registry: dict[str, dict[str, object]], requested: str | None) -> str:
    if requested:
        if requested not in registry:
            raise RuntimeError(f"No managed worktree named '{requested}'.")
        return requested
    current = Path(git(Path.cwd(), "rev-parse", "--show-toplevel").stdout.strip()).resolve()
    for slug, entry in registry.items():
        if Path(str(entry.get("path", ""))).resolve() == current:
            return slug
    raise RuntimeError("This checkout is not registered. Pass a managed worktree slug explicitly.")


def write_env_file(path: Path, port: int, data_directory: Path) -> None:
    env_path = path / ".field-worktree.env"
    contents = (
        "# Generated by scripts/worktree.py. Do not commit this file.\n"
        f"FIELD_MCP_PORT={port}\n"
        f"FIELD_DATA_DIR={shlex.quote(str(data_directory))}\n"
    )
    env_path.write_text(contents, encoding="utf-8")


def cmd_create(slug: str) -> None:
    if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", slug):
        raise RuntimeError("Use a lowercase, hyphenated task slug, for example 'reference-search'.")

    main_root, worktree_home = project_roots()
    if git(main_root, "rev-parse", "--verify", "refs/heads/main", check=False).returncode != 0:
        raise RuntimeError("Create the initial local commit on main before creating task worktrees.")
    if git(main_root, "status", "--porcelain").stdout.strip():
        raise RuntimeError("Commit or clear changes in main before creating a task worktree.")

    branch = f"{BRANCH_PREFIX}{slug}"
    path = worktree_home / slug
    if path.exists():
        raise RuntimeError(f"Worktree path already exists: {path}")
    if git(main_root, "show-ref", "--verify", "--quiet", f"refs/heads/{branch}", check=False).returncode == 0:
        raise RuntimeError(f"Branch already exists: {branch}")

    with locked_registry(worktree_home) as (registry_path, registry):
        git(main_root, "worktree", "prune")
        registry = {key: value for key, value in registry.items() if Path(str(value.get("path", ""))).exists()}
        used_ports = {int(value["port"]) for value in registry.values() if "port" in value}
        port = next((p for p in range(FIRST_PORT, LAST_PORT + 1) if p not in used_ports and not port_is_busy(p)), None)
        if port is None:
            raise RuntimeError(
                f"No free MCP port remains in {FIRST_PORT}-{LAST_PORT}. Stop unused FIELD instances, then run 'python3 scripts/worktree.py prune'."
            )

        result = git(main_root, "worktree", "add", "-b", branch, str(path), "main", check=False)
        if result.returncode != 0:
            raise RuntimeError(result.stderr.strip() or result.stdout.strip() or "Could not create the Git worktree.")

        data_directory = Path.home() / "Library" / "Application Support" / "Field LAB" / "worktrees" / slug
        now = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")
        try:
            write_env_file(path, port, data_directory)
            registry[slug] = {
                "branch": branch,
                "path": str(path),
                "port": port,
                "data_directory": str(data_directory),
                "active": True,
                "created_at": now,
                "last_seen_at": now,
            }
            write_registry(registry_path, registry)
        except OSError:
            git(main_root, "worktree", "remove", str(path), check=False)
            git(main_root, "branch", "-D", branch, check=False)
            raise

    print(f"Created {branch}")
    print(f"Worktree: {path}")
    print(f"MCP port: {port}")
    print(f"Isolated data: {data_directory}")
    print("Open that worktree in Codex to start the task.")


def cmd_list() -> None:
    _, worktree_home = project_roots()
    with locked_registry(worktree_home) as (_, registry):
        if not registry:
            print("No managed FIELD worktrees.")
            return
        for slug, entry in sorted(registry.items()):
            path = Path(str(entry.get("path", "")))
            branch = str(entry.get("branch", f"{BRANCH_PREFIX}{slug}"))
            active = "active" if entry.get("active", True) else "inactive"
            port = int(entry.get("port", 0))
            listener = "port busy" if port and port_is_busy(port) else "port free"
            checkout = "present" if path.is_dir() else "missing"
            print(f"{slug:24} {branch:32} {port:5} {active:8} {listener:10} {checkout:8} {path}")


def cmd_mark_active(requested: str | None, active: bool) -> None:
    main_root, worktree_home = project_roots()
    with locked_registry(worktree_home) as (registry_path, registry):
        slug = resolve_slug(registry, requested)
        registry[slug]["active"] = active
        registry[slug]["last_seen_at"] = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")
        write_registry(registry_path, registry)
    print(f"Marked {slug} {'active' if active else 'inactive'}.")


def cmd_start(requested: str | None) -> int:
    main_root, worktree_home = project_roots()
    with locked_registry(worktree_home) as (registry_path, registry):
        slug = resolve_slug(registry, requested)
        entry = registry[slug]
        path = Path(str(entry["path"]))
        if not path.is_dir():
            raise RuntimeError(f"Worktree is missing: {path}")
        entry["active"] = True
        entry["last_seen_at"] = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")
        write_registry(registry_path, registry)

    environment = os.environ.copy()
    environment["FIELD_MCP_PORT"] = str(entry["port"])
    environment["FIELD_DATA_DIR"] = str(entry["data_directory"])
    print(f"Starting {slug} on http://127.0.0.1:{entry['port']}/mcp (Ctrl-C to stop)", flush=True)
    return subprocess.call(["swift", "run", "FIELD"], cwd=path, env=environment)


def prune_one(slug: str, main_root: Path, worktree_home: Path) -> bool:
    with locked_registry(worktree_home) as (registry_path, registry):
        entry = registry.get(slug)
        if entry is None:
            return False
        path = Path(str(entry.get("path", ""))).resolve()
        if entry.get("active", True):
            print(f"Skip {slug}: marked active.")
            return False
        if not path.is_dir():
            registry.pop(slug)
            write_registry(registry_path, registry)
            return True
        if path_is_current(path):
            print(f"Skip {slug}: current shell is inside this worktree.")
            return False
        if not worktree_is_clean(path):
            print(f"Skip {slug}: worktree has uncommitted or untracked files.")
            return False
        port = int(entry.get("port", 0))
        if port and port_is_busy(port):
            print(f"Skip {slug}: its assigned port {port} is still in use.")
            return False
        result = git(main_root, "worktree", "remove", str(path), check=False)
        if result.returncode != 0:
            print(f"Skip {slug}: {result.stderr.strip() or 'Git could not remove the worktree.'}")
            return False
        registry.pop(slug)
        write_registry(registry_path, registry)
        print(f"Removed {path}; branch {entry.get('branch')} and data at {entry.get('data_directory')} were kept.")
        return True


def cmd_prune() -> None:
    main_root, worktree_home = project_roots()
    git(main_root, "worktree", "prune")
    with locked_registry(worktree_home) as (_, registry):
        candidates = [slug for slug, entry in sorted(registry.items()) if not entry.get("active", True)]
    if not candidates:
        print("No inactive worktrees are available to prune.")
        return

    for slug in candidates:
        answer = input(f"Remove inactive worktree '{slug}' if clean and stopped? [y/N] ").strip().lower()
        if answer == "y":
            prune_one(slug, main_root, worktree_home)
    print("Branches and isolated data directories are retained; only worktree folders and port reservations are removed.")


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description="Manage FIELD task worktrees and their local development resources.")
    commands = result.add_subparsers(dest="command", required=True)

    create = commands.add_parser("create", help="create a task branch/worktree and reserve its port and data store")
    create.add_argument("slug")

    commands.add_parser("list", help="show ports and activity for managed worktrees")

    start = commands.add_parser("start", help="run the FIELD app with this worktree's port and data directory")
    start.add_argument("slug", nargs="?")

    activate = commands.add_parser("activate", help="mark this worktree active so prune will skip it")
    activate.add_argument("slug", nargs="?")

    deactivate = commands.add_parser("deactivate", help="mark a completed or paused worktree inactive")
    deactivate.add_argument("slug", nargs="?")

    commands.add_parser("prune", help="interactively remove inactive, clean, stopped worktree folders")
    return result


def main() -> int:
    args = parser().parse_args()
    try:
        if args.command == "create":
            cmd_create(args.slug)
            return 0
        if args.command == "list":
            cmd_list()
            return 0
        if args.command == "start":
            return cmd_start(args.slug)
        if args.command == "activate":
            cmd_mark_active(args.slug, True)
            return 0
        if args.command == "deactivate":
            cmd_mark_active(args.slug, False)
            return 0
        if args.command == "prune":
            cmd_prune()
            return 0
    except (EOFError, OSError, RuntimeError, ValueError) as error:
        print(f"worktree: {error}", file=sys.stderr)
        return 1
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
